version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      
jobs:
  test:
    docker:
        - image: appium/appium:latest
    steps:
      - checkout
      - run: appium -v
      - run: node -v
      - run: sudo apt-get install python3-pip
      - run: python --version
