version: 2.1
orbs:
  android: circleci/android@1.0.3
  
workflows:
  test-deploy:
    jobs:
#       - test
      - test2
      
jobs:
    test:
      docker:
        - image: appium/appium:latest
      steps:
        - checkout
        - run: appium -v
        - run: node -v
        - run: python3 --version
        - run: npm install -g appium-doctor
        - run: appium-doctor
     
    test2:
      docker:
        - image: circleci/android:api-30-node
      steps:
        - checkout
        
              
              
              
