version: 2.1
orbs:
  android: circleci/android@1.0.3
  
workflows:
  test-deploy:
    jobs:
      - test2
      
jobs:
    test:
      docker:
        - image: appium/appium:latest
      steps:
        - checkout
        - run: appium -v
        - run: node -v
        - run: python3 --version
        - run: npm install -g appium-doctor
        - run: appium-doctor
        - run: appium
        
    test2:
      docker:
        - image: budtmo/docker-android-x86-8.1:latest
      steps:
        - checkout
        - run: adb devices
        - run: docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 --name android-container-appium budtmo/docker-android-real-device
        - run: adb devices

              
              
              
