version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      
jobs:
  build:
    test:
      docker:
          - image: appium/appium:latest
      steps:
        - checkout
        - run: appium -v
        - run: node -v
        - run: python3 --version
