version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      
jobs:
  test:
    docker:
        - image: appium/appium:latest
        - image: cimg/node:16.3.0
    steps:
      - checkout
      - run: appium -v
      - run: node -v
