version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      
jobs:
  build:
    test:
      docker:
          - image: appium/appium:latest
          - image: cimg/python:3.9.5
      steps:
        - checkout
        - run: appium -v
        - run: node -v
        - run: sudo apt-get install python3-pip
        - run: python --version
